# Generated by Django 5.2.1 on 2025-06-10 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='previous_return_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
